{% set name = "django-js-asset" %}
{% set version = "2.2.0" %}
{% set sha256 = "0c57a82cae2317e83951d956110ce847f58ff0cdc24e314dbc18b35033917e94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django

test:
  imports:
    - js_asset
    - js_asset.js

about:
  home: https://github.com/matthiask/django-js-asset
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'script tag with additional attributes for django.forms.Media'
  description: |
    script tag with additional attributes for django.forms.Media
  doc_url: https://github.com/matthiask/django-js-asset
  dev_url: https://github.com/matthiask/django-js-asset

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
