schema_version: 1

context:
  name: django-js-asset
  version: "4.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_js_asset-${{ version }}.tar.gz
  sha256: 51ad1060115bf741bef88dc1287ca7f70e1d6ea7cf935f52a34f39eca9bd9db1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2

tests:
  - python:
      imports:
        - js_asset
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Script tag with additional attributes for django.forms.Media.
  homepage: https://github.com/matthiask/django-js-asset

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - thewchan
