schema_version: 1

context:
  name: django-js-asset
  version: 3.1.2
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_js_asset-${{ version }}.tar.gz
  sha256: 1fc7584199ed1941ed7c8e7b87ca5524bb0f2ba941561d2a104e88ee9f07bedd

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2

tests:
  - python:
      imports:
        - js_asset
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Script tag with additional attributes for django.forms.Media.
  homepage: https://github.com/matthiask/django-js-asset

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - thewchan
